const LOAD_TASKS_START = 'Tasks/LOAD_TASKS_START';
const LOAD_TASKS_SUCCESS = 'Tasks/LOAD_TASKS_SUCCESS';
const LOAD_TASKS_FAIL = 'Tasks/LOAD_TASKS_FAIL';

const UNLOAD_ALL_TASKS = 'Tasks/UNLOAD_ALL_TASKS';

const UPDATE_TASK_START = 'Tasks/UPDATE_TASK_START';
const UPDATE_TASK_SUCCESS = 'Tasks/UPDATE_TASK_SUCCESS';
const UPDATE_TASK_FAIL = 'Tasks/UPDATE_TASK_FAIL';

const CREATE_TASK_START = 'Tasks/CREATE_TASK_START';
const CREATE_TASK_SUCCESS = 'Tasks/CREATE_TASK_SUCCESS';
const CREATE_TASK_FAIL = 'Tasks/CREATE_TASK_FAIL';

const DELETE_TASK_START = 'Tasks/DELETE_TASK_START';
const DELETE_TASK_SUCCESS = 'Tasks/DELETE_TASK_SUCCESS';
const DELETE_TASK_FAIL = 'Tasks/DELETE_TASK_FAIL';

export default {
  LOAD_TASKS_START,
  LOAD_TASKS_SUCCESS,
  LOAD_TASKS_FAIL,
  UNLOAD_ALL_TASKS,
  UPDATE_TASK_START,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_FAIL,
  CREATE_TASK_START,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAIL,
  DELETE_TASK_START,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAIL,
};
