const LOAD_TASKS_START = 'Tasks/LOAD_TASKS_START';
const LOAD_TASKS_SUCCESS = 'Tasks/LOAD_TASKS_SUCCESS';
const LOAD_TASKS_FAIL = 'Tasks/LOAD_TASKS_FAIL';

const UNLOAD_ALL_TASKS = 'Tasks/UNLOAD_ALL_TASKS';

export default {
  LOAD_TASKS_START,
  LOAD_TASKS_SUCCESS,
  LOAD_TASKS_FAIL,
  UNLOAD_ALL_TASKS,
};
