export const SET_WORKING_TIME = 'Settings/SET_WORKING_TIME';
export const SET_DEFAULT_EVENTS_SETTINGS = 'Settings/SET_DEFAULT_EVENTS_SETTINGS';
export const SWITCH_SYNC_TO_GOOGLE_CALENDAR = 'Settings/SWITCH_SYNC_TO_GOOGLE_CALENDAR';
