const LOAD_EVENTS_START = 'Events/LOAD_EVENTS_START';
const LOAD_EVENTS_SUCCESS = 'Events/LOAD_EVENTS_SUCCESS';
const LOAD_EVENTS_FAIL = 'Events/LOAD_EVENTS_FAIL';

const LOAD_SINGLE_EVENT_START = 'Events/LOAD_SINGLE_EVENT_START';
const LOAD_SINGLE_EVENT_SUCCESS = 'Events/LOAD_SINGLE_EVENT_SUCCESS';
const LOAD_SINGLE_EVENT_FAIL = 'Events/LOAD_SINGLE_EVENT_FAIL';

const REMOVE_SINGLE_EVENT = 'Events/REMOVE_SINGLE_EVENT';

const UPDATE_SINGLE_EVENT_START = 'Events/UPDATE_SINGLE_EVENT_START';
const UPDATE_SINGLE_EVENT_SUCCESS = 'Events/UPDATE_SINGLE_EVENT_SUCCESS';
const UPDATE_SINGLE_EVENT_FAIL = 'Events/UPDATE_SINGLE_EVENT_FAIL';

export default {
  LOAD_EVENTS_START,
  LOAD_EVENTS_SUCCESS,
  LOAD_EVENTS_FAIL,
  LOAD_SINGLE_EVENT_START,
  LOAD_SINGLE_EVENT_SUCCESS,
  LOAD_SINGLE_EVENT_FAIL,
  REMOVE_SINGLE_EVENT,
  UPDATE_SINGLE_EVENT_START,
  UPDATE_SINGLE_EVENT_SUCCESS,
  UPDATE_SINGLE_EVENT_FAIL,
};
