const LOAD_EVENTS_START = 'Events/LOAD_EVENTS_START';
const LOAD_EVENTS_SUCCESS = 'Events/LOAD_EVENTS_SUCCESS';
const LOAD_EVENTS_FAIL = 'Events/LOAD_EVENTS_FAIL';
const DELETE_EVENT_START = 'Events/DELETE_EVENT_START';
const DELETE_EVENT_SUCCESS = 'Events/DELETE_EVENT_SUCCESS';
const DELETE_EVENT_FAIL = 'Events/DELETE_EVENT_FAIL';

const LOAD_SINGLE_EVENT_START = 'Events/LOAD_SINGLE_EVENT_START';
const LOAD_SINGLE_EVENT_SUCCESS = 'Events/LOAD_SINGLE_EVENT_SUCCESS';
const LOAD_SINGLE_EVENT_FAIL = 'Events/LOAD_SINGLE_EVENT_FAIL';

const REMOVE_SINGLE_EVENT = 'Events/REMOVE_SINGLE_EVENT';

const UPDATE_SINGLE_EVENT_START = 'Events/UPDATE_SINGLE_EVENT_START';
const UPDATE_SINGLE_EVENT_SUCCESS = 'Events/UPDATE_SINGLE_EVENT_SUCCESS';
const UPDATE_SINGLE_EVENT_FAIL = 'Events/UPDATE_SINGLE_EVENT_FAIL';

const CREATE_SINGLE_EVENT_START = 'Events/CREATE_SINGLE_EVENT_START';
const CREATE_SINGLE_EVENT_SUCCESS = 'Events/CREATE_SINGLE_EVENT_SUCCESS';
const CREATE_SINGLE_EVENT_FAIL = 'Events/CREATE_SINGLE_EVENT_FAIL';

const RESTORE_EVENTS_STATE = 'Events/RESTORE_EVENTS_STATE';
const SET_FILTER = 'Events/SET_FILTER';

export default {
  LOAD_EVENTS_START,
  LOAD_EVENTS_SUCCESS,
  LOAD_EVENTS_FAIL,
  LOAD_SINGLE_EVENT_START,
  LOAD_SINGLE_EVENT_SUCCESS,
  LOAD_SINGLE_EVENT_FAIL,
  REMOVE_SINGLE_EVENT,
  UPDATE_SINGLE_EVENT_START,
  UPDATE_SINGLE_EVENT_SUCCESS,
  UPDATE_SINGLE_EVENT_FAIL,
  CREATE_SINGLE_EVENT_START,
  CREATE_SINGLE_EVENT_SUCCESS,
  CREATE_SINGLE_EVENT_FAIL,
  DELETE_EVENT_START,
  DELETE_EVENT_SUCCESS,
  DELETE_EVENT_FAIL,
  RESTORE_EVENTS_STATE,
  SET_FILTER,
};
