const LOAD_GOALS_START = 'Goals/LOAD_GOALS_START';
const LOAD_GOALS_SUCCESS = 'Goals/LOAD_GOALS_SUCCESS';
const LOAD_GOALS_FAIL = 'Goals/LOAD_GOALS_FAIL';
const DELETE_GOAL_START = 'Goals/DELETE_GOAL_START';
const DELETE_GOAL_SUCCESS = 'Goals/DELETE_GOAL_SUCCESS';
const DELETE_GOAL_FAIL = 'Goals/DELETE_GOAL_FAIL';

export default {
  LOAD_GOALS_START,
  LOAD_GOALS_SUCCESS,
  LOAD_GOALS_FAIL,
  DELETE_GOAL_START,
  DELETE_GOAL_SUCCESS,
  DELETE_GOAL_FAIL,
};
