const LOAD_GOALS_START = 'Goals/LOAD_GOALS_START';
const LOAD_GOALS_SUCCESS = 'Goals/LOAD_GOALS_SUCCESS';
const LOAD_GOALS_FAIL = 'Goals/LOAD_GOALS_FAIL';
const DELETE_GOAL_START = 'Goals/DELETE_GOAL_START';
const DELETE_GOAL_SUCCESS = 'Goals/DELETE_GOAL_SUCCESS';
const DELETE_GOAL_FAIL = 'Goals/DELETE_GOAL_FAIL';

const RESTORE_GOALS_STATE = 'Goals/RESTORE_GOALS_STATE';

const LOAD_SINGLE_GOAL_START = 'Goals/LOAD_SINGLE_GOAL_START';
const LOAD_SINGLE_GOAL_SUCCESS = 'Goals/LOAD_SINGLE_GOAL_SUCCESS';
const LOAD_SINGLE_GOAL_FAIL = 'Goals/LOAD_SINGLE_GOAL_FAIL';

const REMOVE_SINGLE_GOAL = 'Goals/REMOVE_SINGLE_GOAL';

const UPDATE_SINGLE_GOAL_START = 'Goals/UPDATE_SINGLE_GOAL_START';
const UPDATE_SINGLE_GOAL_SUCCESS = 'Goals/UPDATE_SINGLE_GOAL_SUCCESS';
const UPDATE_SINGLE_GOAL_FAIL = 'Goals/UPDATE_SINGLE_GOAL_FAIL';

const CREATE_SINGLE_GOAL_START = 'Goals/CREATE_SINGLE_GOAL_START';
const CREATE_SINGLE_GOAL_SUCCESS = 'Goals/CREATE_SINGLE_GOAL_SUCCESS';
const CREATE_SINGLE_GOAL_FAIL = 'Goals/CREATE_SINGLE_GOAL_FAIL';

const SEARCH_GOALS = 'Goals/SEARCH_GOALS';

const SHOW_SELECTED_EVENTS_START = 'Goals/SHOW_SELECTED_EVENTS_START';
const SHOW_SELECTED_EVENTS_SUCCES = 'Goals/SHOW_SELECTED_EVENTS_SUCCES';
const SHOW_SELECTED_EVENTS_FAIL = 'Goals/SHOW_SELECTED_EVENTS_FAIL';

const REMOVE_SELECTED_EVENTS = 'Goals/REMOVE_SELECTED_EVENTS';

export default {
  LOAD_GOALS_START,
  LOAD_GOALS_SUCCESS,
  LOAD_GOALS_FAIL,
  DELETE_GOAL_START,
  DELETE_GOAL_SUCCESS,
  DELETE_GOAL_FAIL,
  RESTORE_GOALS_STATE,
  LOAD_SINGLE_GOAL_START,
  LOAD_SINGLE_GOAL_SUCCESS,
  LOAD_SINGLE_GOAL_FAIL,
  REMOVE_SINGLE_GOAL,
  UPDATE_SINGLE_GOAL_START,
  UPDATE_SINGLE_GOAL_SUCCESS,
  UPDATE_SINGLE_GOAL_FAIL,
  CREATE_SINGLE_GOAL_START,
  CREATE_SINGLE_GOAL_SUCCESS,
  CREATE_SINGLE_GOAL_FAIL,
  SEARCH_GOALS,
  SHOW_SELECTED_EVENTS_START,
  SHOW_SELECTED_EVENTS_SUCCES,
  SHOW_SELECTED_EVENTS_FAIL,
  REMOVE_SELECTED_EVENTS,
};
